---
- name: dockercompose for mysql and backend frontend
  hosts: all
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started

    - copy:
        src: docker-compose.yml
        dest: ./docker-compose.yml
        owner: himank
        group: himank
        mode: 0644

    - name: deploy Docker Compose
      docker_compose:
        project_src: ./
        files:
          - docker-compose.yml

