---
- name: Pull docker image of Calculator
  hosts: all
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started

    - copy:
        src: docker-compose.yml
        dest: ./docker-compose.yml
        owner: himank
        group: himank
        mode: 0644

    
        		      
#    - name: running container
#      shell: docker run -it -d himankjn/jobportal
