---
- name: dockercompose for mysql and backend frontend
  hosts: all
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started

    - copy:
        src: docker-compose.yml
        dest: ./docker-compose.yml
        owner: himank
        group: himank
        mode: 0644		      

    - name: running the docker-compose.yml file
      ansible.builtin.shell: docker-compose -f docker-compose.yml up

